use crate::def::Currency;
use crate::Locale::{EnBy, EnEu, EnIn, EnUs};

/// Represents a currency code as specified by the ISO 4217 standard, which defines
/// internationally recognized codes for currencies and funds. This enum also includes
/// codes for certain cryptocurrencies and digital assets, extending beyond traditional
/// ISO 4217 currencies.
///
/// # Examples
///
/// ```
/// use crate::cur::CurrencyCode;
///
/// let currency = CurrencyCode::USD;
/// println!("{:?}", currency); // Outputs: USD
///
/// let crypto = CurrencyCode::BTC;
/// println!("{:?}", crypto); // Outputs: BTC
/// ```
///
/// # Notes
///
/// - Traditional fiat currencies such as `USD`, `EUR`, and `JPY` are included.
/// - Cryptocurrencies and digital assets, such as `BTC` (Bitcoin) and `ETH` (Ethereum),
///   are also represented.
/// - Provides functionality for robust currency handling, making it suitable for financial
///   applications, currency conversions, and cryptocurrency operations.
///
/// # Derive Attributes
///
/// - `Debug`: Allows instances to be formatted using `{:?}` for debugging.
/// - `PartialEq` and `Eq`: Enables equality comparisons between instances.
/// - `Hash`: Makes the enum usable as keys in hash maps.
#[derive(Debug, PartialEq, Eq, Hash)]
pub enum CurrencyCode {
    AED,
    AFN,
    ALL,
    AMD,
    ANG,
    AOA,
    ARS,
    AUD,
    AWG,
    AZN,
    BAM,
    BBD,
    BDT,
    BGN,
    BHD,
    BIF,
    BMD,
    BND,
    BOB,
    BRL,
    BSD,
    BTN,
    BWP,
    BYN,
    BYR,
    BZD,
    CAD,
    CDF,
    CHF,
    CLF,
    CLP,
    CNY,
    COP,
    CRC,
    CUC,
    CUP,
    CVE,
    CZK,
    DJF,
    DKK,
    DOP,
    DZD,
    EGP,
    ERN,
    ETB,
    EUR,
    FJD,
    FKP,
    GBP,
    GEL,
    GHS,
    GIP,
    GMD,
    GNF,
    GTQ,
    GYD,
    HKD,
    HNL,
    HRK,
    HTG,
    HUF,
    IDR,
    ILS,
    INR,
    IQD,
    IRR,
    ISK,
    JMD,
    JOD,
    JPY,
    KES,
    KGS,
    KHR,
    KMF,
    KPW,
    KRW,
    KWD,
    KYD,
    KZT,
    LAK,
    LBP,
    LKR,
    LRD,
    LSL,
    LYD,
    MAD,
    MDL,
    MGA,
    MKD,
    MMK,
    MNT,
    MOP,
    MRU,
    MUR,
    MVR,
    MWK,
    MXN,
    MYR,
    MZN,
    NAD,
    NGN,
    NIO,
    NOK,
    NPR,
    NZD,
    OMR,
    PAB,
    PEN,
    PGK,
    PHP,
    PKR,
    PLN,
    PYG,
    QAR,
    RON,
    ROL,
    RSD,
    RUB,
    RWF,
    SAR,
    SBD,
    SCR,
    SDG,
    SEK,
    SGD,
    SHP,
    SKK,
    SLE,
    SLL,
    SOS,
    SRD,
    SSP,
    STD,
    STN,
    SVC,
    SYP,
    SZL,
    THB,
    TJS,
    TMT,
    TND,
    TOP,
    TRY,
    TTD,
    TWD,
    TZS,
    UAH,
    UGX,
    USD,
    UYU,
    UYW,
    UZS,
    VES,
    VND,
    VUV,
    WST,
    XAF,
    XAG,
    XAU,
    XBA,
    XBB,
    XBC,
    XBD,
    XCD,
    XDR,
    XOF,
    XPD,
    XPF,
    XPT,
    XTS,
    YER,
    ZAR,
    ZMK,
    ZMW,
    ZWL,
    BTC,
    COMP,
    DAI,
    ETH,
    MKR,
    UNI,
    USDC,
    USDT,
    XTZ,
    ZEC,
    BCH,
    BSV,
}



// Automatische Umwandlung von `CurrencyEnum` in `Currency` durch das `From`-Trait
impl From<CurrencyCode> for Currency {
    fn from(currency_code: CurrencyCode) -> Self {
        currency_code.as_currency()
    }
}

impl CurrencyCode {
    pub fn as_currency(&self) -> Currency {
        match self {
            CurrencyCode::AED => Currency {
                exponent: 2,
                code: "AED",
                locale: EnUs,
                minor_units: 25,
                name: "United Arab Emirates Dirham",
                symbol: "د.إ",
                symbol_first: false,
            },
            CurrencyCode::AFN => Currency {
                exponent: 2,
                code: "AFN",
                locale: EnUs,
                minor_units: 100,
                name: "Afghan Afghani",
                symbol: "؋",
                symbol_first: false,
            },
            CurrencyCode::ALL => Currency {
                exponent: 2,
                code: "ALL",
                locale: EnEu,
                minor_units: 1,
                name: "Albanian lek",
                symbol: "L",
                symbol_first: false,
            },
            CurrencyCode::AMD => Currency {
                exponent: 2,
                code: "AMD",
                locale: EnUs,
                minor_units: 10,
                name: "Armenian Dram",
                symbol: "դր.",
                symbol_first: false,
            },
            CurrencyCode::ANG => Currency {
                exponent: 2,
                code: "ANG",
                locale: EnUs,
                minor_units: 1,
                name: "Netherlands Antillean Gulden",
                symbol: "ƒ",
                symbol_first: false,
            },
            CurrencyCode::AOA => Currency {
                exponent: 2,
                code: "AOA",
                locale: EnUs,
                minor_units: 10,
                name: "Angolan Kwanza",
                symbol: "Kz",
                symbol_first: false,
            },
            CurrencyCode::ARS => Currency {
                exponent: 2,
                code: "ARS",
                locale: EnEu,
                minor_units: 1,
                name: "Argentine Peso",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::AUD => Currency {
                exponent: 2,
                code: "AUD",
                locale: EnUs,
                minor_units: 5,
                name: "Australian Dollar",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::AWG => Currency {
                exponent: 2,
                code: "AWG",
                locale: EnUs,
                minor_units: 5,
                name: "Aruban Florin",
                symbol: "ƒ",
                symbol_first: false,
            },
            CurrencyCode::AZN => Currency {
                exponent: 2,
                code: "AZN",
                locale: EnUs,
                minor_units: 1,
                name: "Azerbaijani Manat",
                symbol: "₼",
                symbol_first: true,
            },
            CurrencyCode::BAM => Currency {
                exponent: 2,
                code: "BAM",
                locale: EnUs,
                minor_units: 5,
                name: "Bosnia and Herzegovina Convertible Mark",
                symbol: "KM",
                symbol_first: true,
            },
            CurrencyCode::BBD => Currency {
                exponent: 2,
                code: "BBD",
                locale: EnUs,
                minor_units: 1,
                name: "Barbadian Dollar",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::BDT => Currency {
                exponent: 2,
                code: "BDT",
                locale: EnIn,
                minor_units: 1,
                name: "Bangladeshi Taka",
                symbol: "৳",
                symbol_first: true,
            },
            CurrencyCode::BGN => Currency {
                exponent: 2,
                code: "BGN",
                locale: EnIn,
                minor_units: 1,
                name: "Bulgarian Lev",
                symbol: "лв.",
                symbol_first: false,
            },
            CurrencyCode::BHD => Currency {
                exponent: 3,
                code: "BHD",
                locale: EnUs,
                minor_units: 5,
                name: "Bahraini Dinar",
                symbol: "د.ب",
                symbol_first: true,
            },
            CurrencyCode::BIF => Currency {
                exponent: 0,
                code: "BIF",
                locale: EnUs,
                minor_units: 100,
                name: "Burundian Franc",
                symbol: "Fr",
                symbol_first: false,
            },
            CurrencyCode::BMD => Currency {
                exponent: 2,
                code: "BMD",
                locale: EnUs,
                minor_units: 1,
                name: "Bermudian Dollar",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::BND => Currency {
                exponent: 2,
                code: "BND",
                locale: EnUs,
                minor_units: 1,
                name: "Brunei Dollar",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::BOB => Currency {
                exponent: 2,
                code: "BOB",
                locale: EnUs,
                minor_units: 10,
                name: "Bolivian Boliviano",
                symbol: "Bs.",
                symbol_first: true,
            },
            CurrencyCode::BRL => Currency {
                exponent: 2,
                code: "BRL",
                locale: EnUs,
                minor_units: 5,
                name: "Brazilian real",
                symbol: "R$",
                symbol_first: true,
            },
            CurrencyCode::BSD => Currency {
                exponent: 2,
                code: "BSD",
                locale: EnUs,
                minor_units: 1,
                name: "Bahamian Dollar",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::BTN => Currency {
                exponent: 2,
                code: "BTN",
                locale: EnUs,
                minor_units: 5,
                name: "Bhutanese Ngultrum",
                symbol: "Nu.",
                symbol_first: false,
            },
            CurrencyCode::BWP => Currency {
                exponent: 2,
                code: "BWP",
                locale: EnUs,
                minor_units: 5,
                name: "Botswana Pula",
                symbol: "P",
                symbol_first: true,
            },
            CurrencyCode::BYN => Currency {
                exponent: 2,
                code: "BYN",
                locale: EnBy,
                minor_units: 1,
                name: "Belarusian Ruble",
                symbol: "Br",
                symbol_first: false,
            },
            CurrencyCode::BYR => Currency {
                exponent: 0,
                code: "BYR",
                locale: EnBy,
                minor_units: 100,
                name: "Belarusian Ruble",
                symbol: "Br",
                symbol_first: false,
            },
            CurrencyCode::BZD => Currency {
                exponent: 2,
                code: "BZD",
                locale: EnUs,
                minor_units: 1,
                name: "Belize Dollar",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::CAD => Currency {
                exponent: 2,
                code: "CAD",
                locale: EnUs,
                minor_units: 5,
                name: "Canadian Dollar",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::CDF => Currency {
                exponent: 2,
                code: "CDF",
                locale: EnUs,
                minor_units: 1,
                name: "Congolese Franc",
                symbol: "Fr",
                symbol_first: false,
            },
            CurrencyCode::CHF => Currency {
                exponent: 2,
                code: "CHF",
                locale: EnUs,
                minor_units: 5,
                name: "Swiss Franc",
                symbol: "Fr",
                symbol_first: true,
            },
            CurrencyCode::CLF => Currency {
                exponent: 4,
                code: "CLF",
                locale: EnEu,
                minor_units: 5,
                name: "Unidad de Fomento",
                symbol: "UF",
                symbol_first: true,
            },
            CurrencyCode::CLP => Currency {
                exponent: 0,
                code: "CLP",
                locale: EnEu,
                minor_units: 1,
                name: "Chilean Peso",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::CNY => Currency {
                exponent: 2,
                code: "CNY",
                locale: EnUs,
                minor_units: 1,
                name: "Chinese Renminbi Yuan",
                symbol: "¥",
                symbol_first: true,
            },
            CurrencyCode::COP => Currency {
                exponent: 2,
                code: "COP",
                locale: EnEu,
                minor_units: 20,
                name: "Colombian Peso",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::CRC => Currency {
                exponent: 2,
                code: "CRC",
                locale: EnEu,
                minor_units: 500, // TODO - Investigate
                name: "Costa Rican Colón",
                symbol: "₡",
                symbol_first: true,
            },
            CurrencyCode::CUC => Currency {
                exponent: 2,
                code: "CUC",
                locale: EnUs,
                minor_units: 1,
                name: "Cuban Convertible Peso",
                symbol: "$",
                symbol_first: false,
            },
            CurrencyCode::CUP => Currency {
                exponent: 2,
                code: "CUP",
                locale: EnUs,
                minor_units: 1,
                name: "Cuban Peso",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::CVE => Currency {
                exponent: 2,
                code: "CVE",
                locale: EnUs,
                minor_units: 100,
                name: "Cape Verdean Escudo",
                symbol: "$",
                symbol_first: false,
            },
            CurrencyCode::CZK => Currency {
                exponent: 2,
                code: "CZK",
                locale: EnBy,
                minor_units: 100,
                name: "Czech Koruna",
                symbol: "Kč",
                symbol_first: false,
            },
            CurrencyCode::DJF => Currency {
                exponent: 0,
                code: "DJF",
                locale: EnUs,
                minor_units: 100,
                name: "Djiboutian Franc",
                symbol: "Fdj",
                symbol_first: false,
            },
            CurrencyCode::DKK => Currency {
                exponent: 2,
                code: "DKK",
                locale: EnEu,
                minor_units: 50,
                name: "Danish Krone",
                symbol: "kr.",
                symbol_first: false,
            },
            CurrencyCode::DOP => Currency {
                exponent: 2,
                code: "DOP",
                locale: EnUs,
                minor_units: 100,
                name: "Dominican Peso",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::DZD => Currency {
                exponent: 2,
                code: "DZD",
                locale: EnUs,
                minor_units: 100,
                name: "Algerian Dinar",
                symbol: "د.ج",
                symbol_first: false,
            },
            CurrencyCode::EGP => Currency {
                exponent: 2,
                code: "EGP",
                locale: EnUs,
                minor_units: 25,
                name: "Egyptian Pound",
                symbol: "ج.م",
                symbol_first: true,
            },
            CurrencyCode::ERN => Currency {
                exponent: 2,
                code: "ERN",
                locale: EnUs,
                minor_units: 1,
                name: "Eritrean Nakfa",
                symbol: "Nfk",
                symbol_first: false,
            },
            CurrencyCode::ETB => Currency {
                exponent: 2,
                code: "ETB",
                locale: EnUs,
                minor_units: 1,
                name: "Ethiopian Birr",
                symbol: "Br",
                symbol_first: false,
            },
            CurrencyCode::EUR => Currency {
                exponent: 2,
                code: "EUR",
                locale: EnEu,
                minor_units: 1,
                name: "Euro",
                symbol: "€",
                symbol_first: true,
            },
            CurrencyCode::FJD => Currency {
                exponent: 2,
                code: "FJD",
                locale: EnEu,
                minor_units: 5,
                name: "Fijian Dollar",
                symbol: "$",
                symbol_first: false,
            },
            CurrencyCode::FKP => Currency {
                exponent: 2,
                code: "FKP",
                locale: EnEu,
                minor_units: 1,
                name: "Falkland Pound",
                symbol: "£",
                symbol_first: false,
            },
            CurrencyCode::GBP => Currency {
                exponent: 2,
                code: "GBP",
                locale: EnUs,
                minor_units: 1,
                name: "British Pound",
                symbol: "£",
                symbol_first: true,
            },
            CurrencyCode::GEL => Currency {
                exponent: 2,
                code: "GEL",
                locale: EnUs,
                minor_units: 1,
                name: "Georgian Lari",
                symbol: "ლ",
                symbol_first: false,
            },
            CurrencyCode::GHS => Currency {
                exponent: 2,
                code: "GHS",
                locale: EnUs,
                minor_units: 1,
                name: "Ghanaian Cedi",
                symbol: "₵",
                symbol_first: true,
            },
            CurrencyCode::GIP => Currency {
                exponent: 2,
                code: "GIP",
                locale: EnUs,
                minor_units: 1,
                name: "Gibraltar Pound",
                symbol: "£",
                symbol_first: true,
            },
            CurrencyCode::GMD => Currency {
                exponent: 2,
                code: "GMD",
                locale: EnUs,
                minor_units: 1,
                name: "Gambian Dalasi",
                symbol: "D",
                symbol_first: false,
            },
            CurrencyCode::GNF => Currency {
                exponent: 0,
                code: "GNF",
                locale: EnUs,
                minor_units: 100,
                name: "Guinean Franc",
                symbol: "Fr",
                symbol_first: false,
            },
            CurrencyCode::GTQ => Currency {
                exponent: 2,
                code: "GTQ",
                locale: EnUs,
                minor_units: 1,
                name: "Guatemalan Quetzal",
                symbol: "Q",
                symbol_first: true,
            },
            CurrencyCode::GYD => Currency {
                exponent: 2,
                code: "GYD",
                locale: EnUs,
                minor_units: 100,
                name: "Guyanese Dollar",
                symbol: "$",
                symbol_first: false,
            },
            CurrencyCode::HKD => Currency {
                exponent: 2,
                code: "HKD",
                locale: EnUs,
                minor_units: 10,
                name: "Hong Kong Dollar",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::HNL => Currency {
                exponent: 2,
                code: "HNL",
                locale: EnUs,
                minor_units: 5,
                name: "Honduran Lempira",
                symbol: "L",
                symbol_first: true,
            },
            CurrencyCode::HRK => Currency {
                exponent: 2,
                code: "HRK",
                locale: EnEu,
                minor_units: 1,
                name: "Croatian Kuna",
                symbol: "kn",
                symbol_first: false,
            },
            CurrencyCode::HTG => Currency {
                exponent: 2,
                code: "HTG",
                locale: EnUs,
                minor_units: 5,
                name: "Haitian Gourde",
                symbol: "G",
                symbol_first: false,
            },
            CurrencyCode::HUF => Currency {
                exponent: 0,
                code: "HUF",
                locale: EnBy,
                minor_units: 5,
                name: "Hungarian Forint",
                symbol: "Ft",
                symbol_first: false,
            },
            CurrencyCode::IDR => Currency {
                exponent: 2,
                code: "IDR",
                locale: EnUs,
                minor_units: 5000,
                name: "Indonesian Rupiah",
                symbol: "Rp",
                symbol_first: true,
            },
            CurrencyCode::ILS => Currency {
                exponent: 2,
                code: "ILS",
                locale: EnUs,
                minor_units: 10,
                name: "Israeli New Sheqel",
                symbol: "₪",
                symbol_first: true,
            },
            CurrencyCode::INR => Currency {
                exponent: 2,
                code: "INR",
                locale: EnIn,
                minor_units: 50,
                name: "Indian Rupee",
                symbol: "₹",
                symbol_first: true,
            },
            CurrencyCode::IQD => Currency {
                exponent: 3,
                code: "IQD",
                locale: EnUs,
                minor_units: 50000,
                name: "Iraqi Dinar",
                symbol: "ع.د",
                symbol_first: false,
            },
            CurrencyCode::IRR => Currency {
                exponent: 2,
                code: "IRR",
                locale: EnUs,
                minor_units: 5000,
                name: "Iranian Rial",
                symbol: "﷼",
                symbol_first: true,
            },
            CurrencyCode::ISK => Currency {
                exponent: 0,
                code: "ISK",
                locale: EnEu,
                minor_units: 1,
                name: "Icelandic Króna",
                symbol: "kr.",
                symbol_first: true,
            },
            CurrencyCode::JMD => Currency {
                exponent: 2,
                code: "JMD",
                locale: EnUs,
                minor_units: 1,
                name: "Jamaican Dollar",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::JOD => Currency {
                exponent: 3,
                code: "JOD",
                locale: EnUs,
                minor_units: 5,
                name: "Jordanian Dinar",
                symbol: "د.ا",
                symbol_first: true,
            },
            CurrencyCode::JPY => Currency {
                exponent: 0,
                code: "JPY",
                locale: EnUs,
                minor_units: 1,
                name: "Japanese Yen",
                symbol: "¥",
                symbol_first: true,
            },
            CurrencyCode::KES => Currency {
                exponent: 2,
                code: "KES",
                locale: EnUs,
                minor_units: 50,
                name: "Kenyan Shilling",
                symbol: "KSh",
                symbol_first: true,
            },
            CurrencyCode::KGS => Currency {
                exponent: 2,
                code: "KGS",
                locale: EnUs,
                minor_units: 1,
                name: "Kyrgyzstani Som",
                symbol: "som",
                symbol_first: false,
            },
            CurrencyCode::KHR => Currency {
                exponent: 2,
                code: "KHR",
                locale: EnUs,
                minor_units: 5000,
                name: "Cambodian Riel",
                symbol: "៛",
                symbol_first: false,
            },
            CurrencyCode::KMF => Currency {
                exponent: 0,
                code: "KMF",
                locale: EnUs,
                minor_units: 100,
                name: "Comorian Franc",
                symbol: "Fr",
                symbol_first: false,
            },
            CurrencyCode::KPW => Currency {
                exponent: 2,
                code: "KPW",
                locale: EnUs,
                minor_units: 1,
                name: "North Korean Won",
                symbol: "₩",
                symbol_first: false,
            },
            CurrencyCode::KRW => Currency {
                exponent: 0,
                code: "KRW",
                locale: EnUs,
                minor_units: 1,
                name: "South Korean Won",
                symbol: "₩",
                symbol_first: true,
            },
            CurrencyCode::KWD => Currency {
                exponent: 3,
                code: "KWD",
                locale: EnUs,
                minor_units: 5,
                name: "Kuwaiti Dinar",
                symbol: "د.ك",
                symbol_first: true,
            },
            CurrencyCode::KYD => Currency {
                exponent: 2,
                code: "KYD",
                locale: EnUs,
                minor_units: 1,
                name: "Cayman Islands Dollar",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::KZT => Currency {
                exponent: 2,
                code: "KZT",
                locale: EnUs,
                minor_units: 100,
                name: "Kazakhstani Tenge",
                symbol: "₸",
                symbol_first: false,
            },
            CurrencyCode::LAK => Currency {
                exponent: 2,
                code: "LAK",
                locale: EnUs,
                minor_units: 10,
                name: "Lao Kip",
                symbol: "₭",
                symbol_first: false,
            },
            CurrencyCode::LBP => Currency {
                exponent: 2,
                code: "LBP",
                locale: EnUs,
                minor_units: 25000,
                name: "Lebanese Pound",
                symbol: "ل.ل",
                symbol_first: true,
            },
            CurrencyCode::LKR => Currency {
                exponent: 2,
                code: "LKR",
                locale: EnUs,
                minor_units: 100,
                name: "Sri Lankan Rupee",
                symbol: "₨",
                symbol_first: false,
            },
            CurrencyCode::LRD => Currency {
                exponent: 2,
                code: "LRD",
                locale: EnUs,
                minor_units: 5,
                name: "Liberian Dollar",
                symbol: "$",
                symbol_first: false,
            },
            CurrencyCode::LSL => Currency {
                exponent: 2,
                code: "LSL",
                locale: EnUs,
                minor_units: 1,
                name: "Lesotho Loti",
                symbol: "L",
                symbol_first: false,
            },
            CurrencyCode::LYD => Currency {
                exponent: 3,
                code: "LYD",
                locale: EnUs,
                minor_units: 50,
                name: "Libyan Dinar",
                symbol: "ل.د",
                symbol_first: false,
            },
            CurrencyCode::MAD => Currency {
                exponent: 2,
                code: "MAD",
                locale: EnUs,
                minor_units: 1,
                name: "Moroccan Dirham",
                symbol: "د.م.",
                symbol_first: false,
            },
            CurrencyCode::MDL => Currency {
                exponent: 2,
                code: "MDL",
                locale: EnUs,
                minor_units: 1,
                name: "Moldovan Leu",
                symbol: "L",
                symbol_first: false,
            },
            CurrencyCode::MGA => Currency {
                exponent: 1, // TODO - exponent is 1/5th need to represent somehow
                code: "MGA",
                locale: EnUs,
                minor_units: 1,
                name: "Malagasy Ariary",
                symbol: "Ar",
                symbol_first: true,
            },
            CurrencyCode::MKD => Currency {
                exponent: 2,
                code: "MKD",
                locale: EnUs,
                minor_units: 100,
                name: "Macedonian Denar",
                symbol: "ден",
                symbol_first: false,
            },
            CurrencyCode::MMK => Currency {
                exponent: 2,
                code: "MMK",
                locale: EnUs,
                minor_units: 50,
                name: "Myanmar Kyat",
                symbol: "K",
                symbol_first: false,
            },
            CurrencyCode::MNT => Currency {
                exponent: 2,
                code: "MNT",
                locale: EnUs,
                minor_units: 2000,
                name: "Mongolian Tögrög",
                symbol: "₮",
                symbol_first: false,
            },
            CurrencyCode::MOP => Currency {
                exponent: 2,
                code: "MOP",
                locale: EnUs,
                minor_units: 10,
                name: "Macanese Pataca",
                symbol: "P",
                symbol_first: false,
            },
            CurrencyCode::MRU => Currency {
                exponent: 1, // TODO - exponent problem of 5
                code: "MRU",
                locale: EnUs,
                minor_units: 1,
                name: "Mauritanian Ouguiya",
                symbol: "UM",
                symbol_first: false,
            },
            CurrencyCode::MUR => Currency {
                exponent: 2,
                code: "MUR",
                locale: EnUs,
                minor_units: 100,
                name: "Mauritian Rupee",
                symbol: "₨",
                symbol_first: true,
            },
            CurrencyCode::MVR => Currency {
                exponent: 2,
                code: "MVR",
                locale: EnUs,
                minor_units: 100,
                name: "Maldivian Rufiyaa",
                symbol: "MVR",
                symbol_first: false,
            },
            CurrencyCode::MWK => Currency {
                exponent: 2,
                code: "MWK",
                locale: EnUs,
                minor_units: 1,
                name: "Malawian Kwacha",
                symbol: "MK",
                symbol_first: false,
            },
            CurrencyCode::MXN => Currency {
                exponent: 2,
                code: "MXN",
                locale: EnUs,
                minor_units: 5,
                name: "Mexican Peso",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::MYR => Currency {
                exponent: 2,
                code: "MYR",
                locale: EnUs,
                minor_units: 5,
                name: "Malaysian Ringgit",
                symbol: "RM",
                symbol_first: true,
            },
            CurrencyCode::MZN => Currency {
                exponent: 2,
                code: "MZN",
                locale: EnUs,
                minor_units: 1,
                name: "Mozambican Metical",
                symbol: "MTn",
                symbol_first: true,
            },
            CurrencyCode::NAD => Currency {
                exponent: 2,
                code: "NAD",
                locale: EnUs,
                minor_units: 5,
                name: "Namibian Dollar",
                symbol: "$",
                symbol_first: false,
            },
            CurrencyCode::NGN => Currency {
                exponent: 2,
                code: "NGN",
                locale: EnUs,
                minor_units: 50,
                name: "Nigerian Naira",
                symbol: "₦",
                symbol_first: true,
            },
            CurrencyCode::NIO => Currency {
                exponent: 2,
                code: "NIO",
                locale: EnUs,
                minor_units: 5,
                name: "Nicaraguan Córdoba",
                symbol: "C$",
                symbol_first: true,
            },
            CurrencyCode::NOK => Currency {
                exponent: 2,
                code: "NOK",
                locale: EnUs,
                minor_units: 100,
                name: "Norwegian Krone",
                symbol: "kr",
                symbol_first: false,
            },
            CurrencyCode::NPR => Currency {
                exponent: 2,
                code: "NPR",
                locale: EnUs,
                minor_units: 1,
                name: "Nepalese Rupee",
                symbol: "रु",
                symbol_first: true,
            },
            CurrencyCode::NZD => Currency {
                exponent: 2,
                code: "NZD",
                locale: EnUs,
                minor_units: 10,
                name: "New Zealand Dollar",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::OMR => Currency {
                exponent: 3,
                code: "OMR",
                locale: EnUs,
                minor_units: 5,
                name: "Omani Rial",
                symbol: "ر.ع.",
                symbol_first: true,
            },
            CurrencyCode::PAB => Currency {
                exponent: 2,
                code: "PAB",
                locale: EnUs,
                minor_units: 1,
                name: "Panamanian Balboa",
                symbol: "B/.",
                symbol_first: true,
            },
            CurrencyCode::PEN => Currency {
                exponent: 2,
                code: "PEN",
                locale: EnUs,
                minor_units: 1,
                name: "Peruvian Sol",
                symbol: "S/",
                symbol_first: true,
            },
            CurrencyCode::PGK => Currency {
                exponent: 2,
                code: "PGK",
                locale: EnUs,
                minor_units: 5,
                name: "Papua New Guinean Kina",
                symbol: "K",
                symbol_first: false,
            },
            CurrencyCode::PHP => Currency {
                exponent: 2,
                code: "PHP",
                locale: EnUs,
                minor_units: 1,
                name: "Philippine Peso",
                symbol: "₱",
                symbol_first: true,
            },
            CurrencyCode::PKR => Currency {
                exponent: 2,
                code: "PKR",
                locale: EnUs,
                minor_units: 100,
                name: "Pakistani Rupee",
                symbol: "₨",
                symbol_first: true,
            },
            CurrencyCode::PLN => Currency {
                exponent: 2,
                code: "PLN",
                locale: EnBy,
                minor_units: 1,
                name: "Polish Złoty",
                symbol: "zł",
                symbol_first: false,
            },
            CurrencyCode::PYG => Currency {
                exponent: 0,
                code: "PYG",
                locale: EnBy,
                minor_units: 5000,
                name: "Paraguayan Guaraní",
                symbol: "₲",
                symbol_first: true,
            },
            CurrencyCode::QAR => Currency {
                exponent: 2,
                code: "QAR",
                locale: EnBy,
                minor_units: 1,
                name: "Qatari Riyal",
                symbol: "ر.ق",
                symbol_first: false,
            },
            CurrencyCode::RON => Currency {
                exponent: 2,
                code: "RON",
                locale: EnEu,
                minor_units: 1,
                name: "Romanian Leu",
                symbol: "RON",
                symbol_first: false,
            },
            CurrencyCode::ROL => Currency {
                exponent: 0,
                code: "ROL",
                locale: EnEu,
                minor_units: 1,
                name: "Romanian Leu",
                symbol: "ROL",
                symbol_first: false,
            },
            CurrencyCode::RSD => Currency {
                exponent: 2,
                code: "RSD",
                locale: EnUs,
                minor_units: 100,
                name: "Serbian Dinar",
                symbol: "РСД",
                symbol_first: true,
            },
            CurrencyCode::RUB => Currency {
                exponent: 2,
                code: "RUB",
                locale: EnEu,
                minor_units: 1,
                name: "Russian Ruble",
                symbol: "₽",
                symbol_first: false,
            },
            CurrencyCode::RWF => Currency {
                exponent: 0,
                code: "RWF",
                locale: EnUs,
                minor_units: 100,
                name: "Rwandan Franc",
                symbol: "FRw",
                symbol_first: false,
            },
            CurrencyCode::SAR => Currency {
                exponent: 2,
                code: "SAR",
                locale: EnUs,
                minor_units: 5,
                name: "Saudi Riyal",
                symbol: "ر.س",
                symbol_first: true,
            },
            CurrencyCode::SBD => Currency {
                exponent: 2,
                code: "SBD",
                locale: EnUs,
                minor_units: 10,
                name: "Solomon Islands Dollar",
                symbol: "$",
                symbol_first: false,
            },
            CurrencyCode::SCR => Currency {
                exponent: 2,
                code: "SCR",
                locale: EnUs,
                minor_units: 1,
                name: "Seychellois Rupee",
                symbol: "₨",
                symbol_first: false,
            },
            CurrencyCode::SDG => Currency {
                exponent: 2,
                code: "SDG",
                locale: EnUs,
                minor_units: 1,
                name: "Sudanese Pound",
                symbol: "£",
                symbol_first: true,
            },
            CurrencyCode::SEK => Currency {
                exponent: 2,
                code: "SEK",
                locale: EnBy,
                minor_units: 100,
                name: "Swedish Krona",
                symbol: "kr",
                symbol_first: false,
            },
            CurrencyCode::SGD => Currency {
                exponent: 2,
                code: "SGD",
                locale: EnUs,
                minor_units: 1,
                name: "Singapore Dollar",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::SHP => Currency {
                exponent: 2,
                code: "SHP",
                locale: EnUs,
                minor_units: 1,
                name: "Saint Helenian Pound",
                symbol: "£",
                symbol_first: false,
            },
            CurrencyCode::SKK => Currency {
                exponent: 2,
                code: "SKK",
                locale: EnUs,
                minor_units: 50,
                name: "Slovak Koruna",
                symbol: "Sk",
                symbol_first: true,
            },
            CurrencyCode::SLE => Currency {
                exponent: 2,
                code: "SLE",
                locale: EnUs,
                minor_units: 1000,
                name: "Sierra Leonean Leone",
                symbol: "Le",
                symbol_first: false,
            },
            CurrencyCode::SLL => Currency {
                exponent: 2,
                code: "SLL",
                locale: EnUs,
                minor_units: 1000,
                name: "Sierra Leonean Leone",
                symbol: "Le",
                symbol_first: false,
            },
            CurrencyCode::SOS => Currency {
                exponent: 2,
                code: "SOS",
                locale: EnUs,
                minor_units: 1,
                name: "Somali Shilling",
                symbol: "Sh",
                symbol_first: false,
            },
            CurrencyCode::SRD => Currency {
                exponent: 2,
                code: "SRD",
                locale: EnUs,
                minor_units: 1,
                name: "Surinamese Dollar",
                symbol: "$",
                symbol_first: false,
            },
            CurrencyCode::SSP => Currency {
                exponent: 2,
                code: "SSP",
                locale: EnUs,
                minor_units: 5,
                name: "South Sudanese Pound",
                symbol: "£",
                symbol_first: false,
            },
            CurrencyCode::STD => Currency {
                exponent: 2,
                code: "STD",
                locale: EnUs,
                minor_units: 10000,
                name: "São Tomé and Príncipe Dobra",
                symbol: "Db",
                symbol_first: false,
            },
            CurrencyCode::STN => Currency {
                exponent: 2,
                code: "STN",
                locale: EnUs,
                minor_units: 10,
                name: "São Tomé and Príncipe Dobra",
                symbol: "Db",
                symbol_first: false,
            },
            CurrencyCode::SVC => Currency {
                exponent: 2,
                code: "SVC",
                locale: EnUs,
                minor_units: 1,
                name: "Salvadoran Colón",
                symbol: "₡",
                symbol_first: true,
            },
            CurrencyCode::SYP => Currency {
                exponent: 2,
                code: "SYP",
                locale: EnUs,
                minor_units: 100,
                name: "Syrian Pound",
                symbol: "£S",
                symbol_first: false,
            },
            CurrencyCode::SZL => Currency {
                exponent: 2,
                code: "SZL",
                locale: EnUs,
                minor_units: 1,
                name: "Swazi Lilangeni",
                symbol: "E",
                symbol_first: true,
            },
            CurrencyCode::THB => Currency {
                exponent: 2,
                code: "THB",
                locale: EnUs,
                minor_units: 1,
                name: "Thai Baht",
                symbol: "฿",
                symbol_first: true,
            },
            CurrencyCode::TJS => Currency {
                exponent: 2,
                code: "TJS",
                locale: EnUs,
                minor_units: 1,
                name: "Tajikistani Somoni",
                symbol: "ЅМ",
                symbol_first: false,
            },
            CurrencyCode::TMT => Currency {
                exponent: 2,
                code: "TMT",
                locale: EnUs,
                minor_units: 1,
                name: "Turkmenistani Manat",
                symbol: "T",
                symbol_first: false,
            },
            CurrencyCode::TND => Currency {
                exponent: 3,
                code: "TND",
                locale: EnUs,
                minor_units: 10,
                name: "Tunisian Dinar",
                symbol: "د.ت",
                symbol_first: false,
            },
            CurrencyCode::TOP => Currency {
                exponent: 2,
                code: "TOP",
                locale: EnUs,
                minor_units: 1,
                name: "Tongan Paʻanga",
                symbol: "T$",
                symbol_first: true,
            },
            CurrencyCode::TRY => Currency {
                exponent: 2,
                code: "TRY",
                locale: EnEu,
                minor_units: 1,
                name: "Turkish Lira",
                symbol: "₺",
                symbol_first: true,
            },
            CurrencyCode::TTD => Currency {
                exponent: 2,
                code: "TTD",
                locale: EnUs,
                minor_units: 1,
                name: "Trinidad and Tobago Dollar",
                symbol: "$",
                symbol_first: false,
            },
            CurrencyCode::TWD => Currency {
                exponent: 2,
                code: "TWD",
                locale: EnUs,
                minor_units: 50,
                name: "New Taiwan Dollar",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::TZS => Currency {
                exponent: 2,
                code: "TZS",
                locale: EnUs,
                minor_units: 5000,
                name: "Tanzanian Shilling",
                symbol: "Sh",
                symbol_first: true,
            },
            CurrencyCode::UAH => Currency {
                exponent: 2,
                code: "UAH",
                locale: EnUs,
                minor_units: 1,
                name: "Ukrainian Hryvnia",
                symbol: "₴",
                symbol_first: false,
            },
            CurrencyCode::UGX => Currency {
                exponent: 0,
                code: "UGX",
                locale: EnUs,
                minor_units: 1000,
                name: "Ugandan Shilling",
                symbol: "USh",
                symbol_first: false,
            },
            CurrencyCode::USD => Currency {
                exponent: 2,
                code: "USD",
                locale: EnUs,
                minor_units: 1,
                name: "United States Dollar",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::UYU => Currency {
                exponent: 2,
                code: "UYU",
                locale: EnEu,
                minor_units: 100,
                name: "Uruguayan Peso",
                symbol: "$U",
                symbol_first: true,
            },
            CurrencyCode::UYW => Currency {
                exponent: 4,
                code: "UYW",
                locale: EnEu,
                minor_units: 1000,
                name: "Unidad Previsional",
                symbol: "UP",
                symbol_first: true,
            },
            CurrencyCode::UZS => Currency {
                exponent: 2,
                code: "UZS",
                locale: EnUs,
                minor_units: 100,
                name: "Uzbekistan Som",
                symbol: "so'm",
                symbol_first: false,
            },
            CurrencyCode::VES => Currency {
                exponent: 2,
                code: "VES",
                locale: EnEu,
                minor_units: 1,
                name: "Venezuelan Bolívar Soberano",
                symbol: "Bs",
                symbol_first: true,
            },
            CurrencyCode::VND => Currency {
                exponent: 0,
                code: "VND",
                locale: EnEu,
                minor_units: 100,
                name: "Vietnamese Đồng",
                symbol: "₫",
                symbol_first: false,
            },
            CurrencyCode::VUV => Currency {
                exponent: 0,
                code: "VUV",
                locale: EnUs,
                minor_units: 1,
                name: "Vanuatu Vatu",
                symbol: "Vt",
                symbol_first: true,
            },
            CurrencyCode::WST => Currency {
                exponent: 2,
                code: "WST",
                locale: EnUs,
                minor_units: 10,
                name: "Samoan Tala",
                symbol: "T",
                symbol_first: false,
            },
            CurrencyCode::XAF => Currency {
                exponent: 0,
                code: "XAF",
                locale: EnUs,
                minor_units: 100,
                name: "Central African Cfa Franc",
                symbol: "CFA",
                symbol_first: false,
            },
            CurrencyCode::XAG => Currency {
                exponent: 0,
                code: "XAG",
                locale: EnUs,
                minor_units: 100,
                name: "Silver (Troy Ounce)",
                symbol: "oz t",
                symbol_first: false,
            },
            CurrencyCode::XAU => Currency {
                exponent: 0,
                code: "XAU",
                locale: EnUs,
                minor_units: 100,
                name: "Gold (Troy Ounce)",
                symbol: "oz t",
                symbol_first: false,
            },
            CurrencyCode::XBA => Currency {
                exponent: 0,
                code: "XBA",
                locale: EnUs,
                minor_units: 100,
                name: "European Composite Unit",
                symbol: "",
                symbol_first: false,
            },
            CurrencyCode::XBB => Currency {
                exponent: 0,
                code: "XBB",
                locale: EnUs,
                minor_units: 100,
                name: "European Monetary Unit",
                symbol: "",
                symbol_first: false,
            },
            CurrencyCode::XBC => Currency {
                exponent: 0,
                code: "XBC",
                locale: EnUs,
                minor_units: 100,
                name: "European Unit of Account 9",
                symbol: "",
                symbol_first: false,
            },
            CurrencyCode::XBD => Currency {
                exponent: 0,
                code: "XBD",
                locale: EnUs,
                minor_units: 100,
                name: "European Unit of Account 17",
                symbol: "",
                symbol_first: false,
            },
            CurrencyCode::XCD => Currency {
                exponent: 2,
                code: "XCD",
                locale: EnUs,
                minor_units: 1,
                name: "East Caribbean Dollar",
                symbol: "$",
                symbol_first: true,
            },
            CurrencyCode::XDR => Currency {
                exponent: 0,
                code: "XDR",
                locale: EnUs,
                minor_units: 100,
                name: "Special Drawing Rights",
                symbol: "SDR",
                symbol_first: false,
            },
            CurrencyCode::XOF => Currency {
                exponent: 0,
                code: "XOF",
                locale: EnUs,
                minor_units: 100,
                name: "West African Cfa Franc",
                symbol: "Fr",
                symbol_first: false,
            },
            CurrencyCode::XPD => Currency {
                exponent: 0,
                code: "XPD",
                locale: EnUs,
                minor_units: 100,
                name: "Palladium",
                symbol: "oz t",
                symbol_first: false,
            },
            CurrencyCode::XPF => Currency {
                exponent: 0,
                code: "XPF",
                locale: EnUs,
                minor_units: 100,
                name: "Cfp Franc",
                symbol: "Fr",
                symbol_first: false,
            },
            CurrencyCode::XPT => Currency {
                exponent: 0,
                code: "XPT",
                locale: EnUs,
                minor_units: 100,
                name: "Platinum",
                symbol: "oz t",
                symbol_first: false,
            },
            CurrencyCode::XTS => Currency {
                exponent: 0,
                code: "XTS",
                locale: EnUs,
                minor_units: 100,
                name: "Codes specifically reserved for testing purposes",
                symbol: "oz t",
                symbol_first: false,
            },
            CurrencyCode::YER => Currency {
                exponent: 2,
                code: "YER",
                locale: EnUs,
                minor_units: 100,
                name: "Yemeni Rial",
                symbol: "﷼",
                symbol_first: false,
            },
            CurrencyCode::ZAR => Currency {
                exponent: 2,
                code: "ZAR",
                locale: EnUs,
                minor_units: 10,
                name: "South African Rand",
                symbol: "R",
                symbol_first: true,
            },
            CurrencyCode::ZMK => Currency {
                exponent: 2,
                code: "ZMK",
                locale: EnUs,
                minor_units: 5,
                name: "Zambian Kwacha",
                symbol: "ZK",
                symbol_first: false,
            },
            CurrencyCode::ZMW => Currency {
                exponent: 2,
                code: "ZMW",
                locale: EnUs,
                minor_units: 5,
                name: "Zambian Kwacha",
                symbol: "K",
                symbol_first: true,
            },
            CurrencyCode::ZWL => Currency {
                exponent: 2,
                code: "ZWL",
                locale: EnUs,
                minor_units: 1,
                name: "Zimbabwe Dollar",
                symbol: "Z$",
                symbol_first: true,
            },
            CurrencyCode::BTC => Currency {
                exponent: 8,
                code: "BTC",
                locale: EnUs,
                minor_units: 100_000_000,
                name: "Bitcoin",
                symbol: "₿",
                symbol_first: true,
            },
            CurrencyCode::COMP => Currency {
                exponent: 18,
                code: "COMP",
                locale: EnUs,
                minor_units: 1_000_000_000_000_000_000,
                name: "Compound",
                symbol: "COMP",
                symbol_first: false,
            },
            CurrencyCode::DAI => Currency {
                exponent: 18,
                code: "DAI",
                locale: EnUs,
                minor_units: 1_000_000_000_000_000_000,
                name: "Dai Stablecoin",
                symbol: "DAI",
                symbol_first: false,
            },
            CurrencyCode::ETH => Currency {
                exponent: 18,
                code: "ETH",
                locale: EnUs,
                minor_units: 1_000_000_000_000_000_000,
                name: "Ethereum",
                symbol: "ETH",
                symbol_first: false,
            },
            CurrencyCode::MKR => Currency {
                exponent: 18,
                code: "MKR",
                locale: EnUs,
                minor_units: 1_000_000_000_000_000_000,
                name: "Maker",
                symbol: "MKR",
                symbol_first: false,
            },
            CurrencyCode::UNI => Currency {
                exponent: 18,
                code: "UNI",
                locale: EnUs,
                minor_units: 1_000_000_000_000_000_000,
                name: "Uniswap",
                symbol: "UNI",
                symbol_first: false,
            },
            CurrencyCode::USDC => Currency {
                exponent: 6,
                code: "USDC",
                locale: EnUs,
                minor_units: 1_000_000,
                name: "USD Coin",
                symbol: "USDC",
                symbol_first: false,
            },
            CurrencyCode::USDT => Currency {
                exponent: 6,
                code: "USDT",
                locale: EnUs,
                minor_units: 1_000_000,
                name: "Tether",
                symbol: "USDT",
                symbol_first: false,
            },
            CurrencyCode::XTZ => Currency {
                exponent: 6,
                code: "XTZ",
                locale: EnUs,
                minor_units: 1_000_000,
                name: "Tezos",
                symbol: "XTZ",
                symbol_first: false,
            },
            CurrencyCode::ZEC => Currency {
                exponent: 8,
                code: "ZEC",
                locale: EnUs,
                minor_units: 100_000_000,
                name: "ZCash",
                symbol: "ZEC",
                symbol_first: false,
            },
            CurrencyCode::BCH => Currency {
                exponent: 8,
                code: "BCH",
                locale: EnUs,
                minor_units: 100_000_000,
                name: "Bitcoin Cash",
                symbol: "BCH",
                symbol_first: false,
            },
            CurrencyCode::BSV => Currency {
                exponent: 8,
                code: "BSV",
                locale: EnUs,
                minor_units: 100_000_000,
                name: "Bitcoin SV",
                symbol: "BSV",
                symbol_first: false,
            },
        }
    }
}
