#![doc = include_str!("../README.md")]

mod error;
mod exchange;
mod format;
mod locale;
mod money;
pub mod currency;
pub mod currencies;

// Include the code generated by build.rs (CURRENCIES and LOCALES maps)
include!(concat!(env!("OUT_DIR"), "/generated_maps.rs"));

pub use currency::*;
pub use error::MoneyError;
pub use exchange::*;
pub use format::*;
pub use money::*;
